#! /bin/sh
### BEGIN INIT INFO
# Provides:          rotor-control
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Rotor control for Gpredict
# Description:       Längere Bechreibung
### END INIT INFO
# Author: Stefan Urban <stefan.urban@live.de>

# Aktionen
case "$1" in
    start)
        /opt/rotor-control/start-rotor-control.sh
        ;;
    stop)
        /opt/rotor-control/stop-rotor-control.sh
        ;;
    restart)
        /opt/rotor-control/stop-rotor-control.sh
        /opt/rotor-control/start-rotor-control.sh
        ;;
    *)
        echo "Usage: rotor-control (start|stop|restart)"
        ;;
esac

exit 0
